In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split #class to validations
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error#to measure the accuracy


#Import the data set

In [2]:
data=pd.read_csv("E:\\Data scienec Master class\\notes\\machine learning\\datasets\\archive (34)\\HousingData.csv")

In [3]:
data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90  11.43  36.2

In [5]:
#split varibles into x and y
x=data.iloc[:,:13].values
y=data.iloc[:,13].values
#value command covert into arrays
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [22]:
#training and testing divide from x and y
#this commnd make above x and y as 2*x and 2*y  then 4 arrays are given
train_test_split(x,y,test_size=0.2,random_state=0)
#random_state is like setseed command


[array([[3.58090000e-01, 0.00000000e+00, 6.20000000e+00, ...,
         3.07000000e+02, 1.74000000e+01, 3.91700000e+02],
        [1.58760000e-01, 0.00000000e+00, 1.08100000e+01, ...,
         3.05000000e+02, 1.92000000e+01, 3.76940000e+02],
        [1.13290000e-01, 3.00000000e+01, 4.93000000e+00, ...,
         3.00000000e+02, 1.66000000e+01, 3.91250000e+02],
        ...,
        [1.50980000e-01, 0.00000000e+00, 1.00100000e+01, ...,
         4.32000000e+02, 1.78000000e+01, 3.94510000e+02],
        [2.29270000e-01, 0.00000000e+00, 1.10839918e+01, ...,
         2.33000000e+02, 1.79000000e+01, 3.92740000e+02],
        [1.39140000e-01, 0.00000000e+00, 4.05000000e+00, ...,
         2.96000000e+02, 1.66000000e+01, 3.96900000e+02]]),
 array([[6.72400000e-02, 0.00000000e+00, 3.24000000e+00, ...,
         4.30000000e+02, 1.69000000e+01, 3.75210000e+02],
        [9.23230000e+00, 0.00000000e+00, 1.81000000e+01, ...,
         6.66000000e+02, 2.02000000e+01, 3.66150000e+02],
        [1.14250000e-01, 

In [23]:
#to acessing each value in array we difine a arraay like below.Then we can call sepreatly each of them
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [24]:
x_train


array([[3.58090000e-01, 0.00000000e+00, 6.20000000e+00, ...,
        3.07000000e+02, 1.74000000e+01, 3.91700000e+02],
       [1.58760000e-01, 0.00000000e+00, 1.08100000e+01, ...,
        3.05000000e+02, 1.92000000e+01, 3.76940000e+02],
       [1.13290000e-01, 3.00000000e+01, 4.93000000e+00, ...,
        3.00000000e+02, 1.66000000e+01, 3.91250000e+02],
       ...,
       [1.50980000e-01, 0.00000000e+00, 1.00100000e+01, ...,
        4.32000000e+02, 1.78000000e+01, 3.94510000e+02],
       [2.29270000e-01, 0.00000000e+00, 1.10839918e+01, ...,
        2.33000000e+02, 1.79000000e+01, 3.92740000e+02],
       [1.39140000e-01, 0.00000000e+00, 4.05000000e+00, ...,
        2.96000000e+02, 1.66000000e+01, 3.96900000e+02]])

In [25]:
#create a objective using LinearRegression
model=LinearRegression()


In [26]:
model.fit(x_train,y_train)#LinearRegression is output

LinearRegression()

In [15]:
model.coef_#beeta 1,2,3,4,5,6,7,8,9,10,11,12

array([ 1.43001008e-01,  1.53728337e-02,  3.88635233e-02,  6.34924335e-01,
        5.09579067e+00, -4.42576783e+00,  7.88526468e-02, -5.15023995e-02,
       -4.04470513e-02,  5.26272007e-04,  2.18825183e-01, -1.47413732e-02])

In [17]:
model.intercept_#interception

32.80070221925997

In [18]:
model.score(x_train,y_train)#R^2 value

0.646231088060397

In [24]:
y_predict=model.predict(x_test)#check whethere how it is diviated from actual value

In [26]:
mean_squared_error(y_predict,y_test)#mean square erorr value

21.59542863139687

In [27]:
np.sqrt(mean_squared_error(y_predict,y_test))#root of mean square erorr

4.647088188467793

In [28]:
x1=np.array([0.00632,18.0,2.31,0.538,6.575,65.2,4.0900,1,296,15.3,369.90,4.98]).reshape(1,12)#dimenshion eka 2 wenna oni api model eka train kre column wise ekak nisa


In [29]:
model.predict(x1)#prediction 

array([-152.36880499])